/* =========================================================
   DADOS.JS — FONTE ÚNICA DE LUGARES
   Esta é a única lista de lugares do Save Date.
   Todas as páginas (explorar, detalhes, salvos, conta e as
   páginas de categoria) usam este arquivo.
   Para adicionar/editar um lugar, edite SOMENTE aqui.
========================================================= */

const lugaresData = [
  {
    id: 1,
    nome: "Família Mancini",
    categoria: "Restaurante",
    emoji: "🍽️",
    imagem: "img/pagRestaurante.jpeg",
    preco: 95,
    avaliacoes: 4.8,
    countAvaliacao: 567,
    localizacao: "Zona sul, São Paulo",
    tags: ["Família", "Casal"],
    descricao: "Restaurante italiano clássico com massas artesanais e ambiente acolhedor para toda a família.",
    endereco: "Rua Exemplo, 123 - São Paulo, SP",
    telefone: "(11) 3333-3333",
    horario: "11h30 - 23h",
    diferenciais: ["Massas artesanais", "Ambiente acolhedor", "Ar condicionado", "Estacionamento", "Vinhos importados"]
  },
  {
    id: 2,
    nome: "O Bar do Seu Zé",
    categoria: "Bar",
    emoji: "🍺",
    imagem: "img/seuze.jpg",
    preco: 45,
    avaliacoes: 4.6,
    countAvaliacao: 324,
    localizacao: "Vila Mariana",
    tags: ["Amigos", "Casal"],
    descricao: "Bar tradicional com cervejas artesanais, drinks clássicos e uma vibe descontraída.",
    endereco: "Avenida Paulista, 456 - São Paulo, SP",
    telefone: "(11) 2222-2222",
    horario: "17h - 02h",
    diferenciais: ["Cervejas artesanais", "Happy hour diário", "Música ao vivo", "Petiscos"]
  },
  {
    id: 3,
    nome: "Gourmet Burguer",
    categoria: "Lanchonete",
    emoji: "🍔",
    imagem: "",
    preco: 35,
    avaliacoes: 4.5,
    countAvaliacao: 412,
    localizacao: "Pinheiros",
    tags: ["Amigos", "Família"],
    descricao: "Hamburgueria com carnes selecionadas, pães caseiros e combinações criativas.",
    endereco: "Rua dos Pinheiros, 789 - São Paulo, SP",
    telefone: "(11) 4444-4444",
    horario: "11h - 22h",
    diferenciais: ["Carnes selecionadas", "Pães caseiros", "Batatas artesanais", "Atendimento rápido"]
  },
  {
    id: 4,
    nome: "Pizzaria do Bairro",
    categoria: "Pizzaria",
    emoji: "🍕",
    imagem: "img/pizzariadobairro.jpg",
    preco: 60,
    avaliacoes: 4.7,
    countAvaliacao: 598,
    localizacao: "Mooca",
    tags: ["Família", "Casal", "Amigos"],
    descricao: "Pizzaria tradicional com forno a lenha, ingredientes frescos e clima informal.",
    endereco: "Rua da Mooca, 321 - São Paulo, SP",
    telefone: "(11) 5555-5555",
    horario: "12h - 23h",
    diferenciais: ["Forno a lenha", "Ingredientes frescos", "Pizzas grandes", "Bom para grupos"]
  },
  {
    id: 5,
    nome: "Café Aconchego",
    categoria: "Café",
    emoji: "☕",
    imagem: "img/cafeaconchego2.jpg",
    preco: 25,
    avaliacoes: 4.9,
    countAvaliacao: 876,
    localizacao: "Vila Madalena",
    tags: ["Casal"],
    descricao: "Café aconchegante com bebidas artesanais, doces caseiros e espaço tranquilo.",
    endereco: "Rua Vila Madalena, 654 - São Paulo, SP",
    telefone: "(11) 6666-6666",
    horario: "07h - 19h",
    diferenciais: ["Café especial", "Doces caseiros", "Wi-Fi grátis", "Ambiente acolhedor"]
  },
  {
    id: 6,
    nome: "Shopping Center VillaGe",
    categoria: "Shopping",
    emoji: "🛍️",
    imagem: "img/bangushopping.jpg",
    preco: 0,
    avaliacoes: 4.4,
    countAvaliacao: 1200,
    localizacao: "Zona norte",
    tags: ["Família", "Amigos"],
    descricao: "Shopping completo com lojas, restaurantes e entretenimento para toda a família.",
    endereco: "Rodovia Anhanguera, Km 25 - São Paulo, SP",
    telefone: "(11) 7777-7777",
    horario: "10h - 22h",
    diferenciais: ["Múltiplas lojas", "Praça de alimentação", "Cinema", "Estacionamento"]
  },
  {
    id: 7,
    nome: "Parque da Independência",
    categoria: "Parque",
    emoji: "🌳",
    imagem: "img/parqueindependencia.jpg",
    preco: 0,
    avaliacoes: 4.6,
    countAvaliacao: 445,
    localizacao: "Ipiranga",
    tags: ["Família", "Casal"],
    descricao: "Parque histórico com áreas verdes, caminhada e espaço para piquenique.",
    endereco: "Avenida Nazaré, 1000 - São Paulo, SP",
    telefone: "(11) 8888-8888",
    horario: "06h - 22h",
    diferenciais: ["Áreas verdes", "Piquenique", "Monumento histórico", "Caminhada"]
  },
  {
    id: 8,
    nome: "Sorveteria Gelato",
    categoria: "Sorveteria",
    emoji: "🍨",
    imagem: "",
    preco: 20,
    avaliacoes: 4.8,
    countAvaliacao: 567,
    localizacao: "Consolação",
    tags: ["Amigos", "Família", "Casal"],
    descricao: "Sorveteria artesanal com sabores variados e receitas italianas tradicionais.",
    endereco: "Avenida Consolação, 111 - São Paulo, SP",
    telefone: "(11) 9999-9999",
    horario: "12h - 22h",
    diferenciais: ["Gelato artesanal", "Sabores sazonais", "Opções leves", "Bom custo-benefício"]
  },
  {
    id: 9,
    nome: "Beer & Vibes",
    categoria: "Bar",
    emoji: "🍻",
    imagem: "img/beerevibe.jpg",
    preco: 50,
    avaliacoes: 4.5,
    countAvaliacao: 289,
    localizacao: "Bom Retiro",
    tags: ["Amigos"],
    descricao: "Bar moderno com cervejas artesanais, música e ambiente descontraído.",
    endereco: "Rua Bom Retiro, 222 - São Paulo, SP",
    telefone: "(11) 1010-1010",
    horario: "17h - 03h",
    diferenciais: ["Cervejas artesanais", "DJ ao vivo", "Ambiente moderno", "Petiscos"]
  },
  {
    id: 10,
    nome: "Lounge Central",
    categoria: "Bar",
    emoji: "🍸",
    imagem: "img/central.jpg",
    preco: 70,
    avaliacoes: 4.5,
    countAvaliacao: 156,
    localizacao: "Centro",
    tags: ["Casal", "Drinks", "Noite"],
    descricao: "Drinks autorais e clima mais calmo para quem quer conversar sem pressa.",
    endereco: "Rua Central, 50 - São Paulo, SP",
    telefone: "(11) 1212-1212",
    horario: "18h - 01h",
    diferenciais: ["Drinks autorais", "Ambiente calmo", "Carta de vinhos", "Bom para conversar"]
  },
  {
    id: 11,
    nome: "Piquenique no Parque",
    categoria: "Parque",
    emoji: "🧺",
    imagem: "img/piquenique.jpg",
    preco: 30,
    avaliacoes: 4.7,
    countAvaliacao: 98,
    localizacao: "Ibirapuera",
    tags: ["Casal", "Econômico", "Ao ar livre"],
    descricao: "Plano econômico: leve lanches, escolha um gramado e aproveite o fim de tarde.",
    endereco: "Parque Ibirapuera - São Paulo, SP",
    telefone: "(11) 0000-0000",
    horario: "06h - 18h",
    diferenciais: ["Ao ar livre", "Econômico", "Ideal para casais", "Fim de tarde"]
  },
  {
    id: 12,
    nome: "Trilha Leve",
    categoria: "Parque",
    emoji: "🥾",
    imagem: "img/trilha.jpg",
    preco: 0,
    avaliacoes: 4.6,
    countAvaliacao: 74,
    localizacao: "Cantareira",
    tags: ["Amigos", "Natureza", "Grátis"],
    descricao: "Caminhada curta para quem quer um programa ativo sem depender de reserva.",
    endereco: "Parque da Cantareira - São Paulo, SP",
    telefone: "(11) 0000-0000",
    horario: "07h - 17h",
    diferenciais: ["Natureza", "Programa ativo", "Grátis", "Sem reserva"]
  },
  {
    id: 13,
    nome: "Shopping Leblon",
    categoria: "Shopping",
    emoji: "🛍️",
    imagem: "img/shoppingLeblon.png",
    preco: 0,
    avaliacoes: 4.6,
    countAvaliacao: 980,
    localizacao: "Leblon, Rio de Janeiro",
    tags: ["Casal", "Cinema", "Restaurantes"],
    descricao: "Lojas, restaurantes e cinema em um ambiente elegante para passeios mais tranquilos.",
    endereco: "Av. Afrânio de Melo Franco, 290 - Rio de Janeiro, RJ",
    telefone: "(21) 2111-2111",
    horario: "10h - 22h",
    diferenciais: ["Cinema", "Restaurantes", "Lojas premium", "Ambiente elegante"]
  },
  {
    id: 14,
    nome: "Barra Shopping",
    categoria: "Shopping",
    emoji: "🛍️",
    imagem: "img/shoppingBarra.jpg",
    preco: 0,
    avaliacoes: 4.5,
    countAvaliacao: 1340,
    localizacao: "Barra da Tijuca, Rio de Janeiro",
    tags: ["Família", "Amigos", "Compras"],
    descricao: "Shopping amplo com praça de alimentação, cinema e várias opções para família.",
    endereco: "Av. das Américas, 4666 - Rio de Janeiro, RJ",
    telefone: "(21) 2222-2222",
    horario: "10h - 22h",
    diferenciais: ["Praça de alimentação", "Cinema", "Amplo", "Bom para família"]
  },
  {
    id: 15,
    nome: "Fashion Mall",
    categoria: "Shopping",
    emoji: "🛍️",
    imagem: "img/fashionMall.webp",
    preco: 0,
    avaliacoes: 4.7,
    countAvaliacao: 760,
    localizacao: "São Conrado, Rio de Janeiro",
    tags: ["Moda", "Restaurantes", "Conforto"],
    descricao: "Boa escolha para restaurante, lojas e programa mais confortável em ambiente fechado.",
    endereco: "Estr. da Gávea, 899 - Rio de Janeiro, RJ",
    telefone: "(21) 3333-3333",
    horario: "10h - 22h",
    diferenciais: ["Moda", "Restaurantes", "Conforto", "Ambiente fechado"]
  },
  {
    id: 16,
    nome: "Casa de Eventos Aurora",
    categoria: "Salão de festas",
    emoji: "🎉",
    imagem: "img/aurora.jpg",
    preco: 180,
    avaliacoes: 4.4,
    countAvaliacao: 64,
    localizacao: "Zona oeste",
    tags: ["Grupo", "Evento", "Reserva"],
    descricao: "Espaço compacto para aniversários, confraternizações e encontros com amigos.",
    endereco: "Rua das Flores, 200 - São Paulo, SP",
    telefone: "(11) 4545-4545",
    horario: "Sob reserva",
    diferenciais: ["Para grupos", "Som e iluminação", "Reserva flexível", "Espaço compacto"]
  },
  {
    id: 17,
    nome: "Salão Jardim",
    categoria: "Salão de festas",
    emoji: "🎊",
    imagem: "img/jardim.jpeg",
    preco: 220,
    avaliacoes: 4.6,
    countAvaliacao: 51,
    localizacao: "Zona sul",
    tags: ["Aniversário", "Família", "Área externa"],
    descricao: "Ambiente para festa pequena com área externa, mesas e espaço para decoração.",
    endereco: "Av. dos Jardins, 800 - São Paulo, SP",
    telefone: "(11) 4646-4646",
    horario: "Sob reserva",
    diferenciais: ["Área externa", "Decoração", "Para família", "Festa pequena"]
  },
  {
    id: 18,
    nome: "Noite com DJ",
    categoria: "Salão de festas",
    emoji: "🎶",
    imagem: "img/dj.jpg",
    preco: 160,
    avaliacoes: 4.3,
    countAvaliacao: 88,
    localizacao: "Centro",
    tags: ["Amigos", "Música", "Noite"],
    descricao: "Opção para grupos que querem música, pista pequena e clima de comemoração.",
    endereco: "Rua da Noite, 10 - São Paulo, SP",
    telefone: "(11) 4747-4747",
    horario: "22h - 04h",
    diferenciais: ["DJ ao vivo", "Pista de dança", "Para grupos", "Clima de festa"]
  },

  /* ---------- LUGARES REAIS (São Paulo) ---------- */
  {
    id: 19,
    nome: "Bar Brahma",
    categoria: "Bar",
    emoji: "🍺",
    imagem: "",
    preco: 70,
    avaliacoes: 4.4,
    countAvaliacao: 18500,
    localizacao: "Centro, São Paulo",
    tags: ["Amigos", "Música ao vivo", "Tradição"],
    descricao: "Bar histórico de 1948 no centro de SP, com samba, chorinho e gastronomia de boteco.",
    endereco: "Av. São João, 677 - Centro, São Paulo, SP",
    telefone: "(11) 3367-3000",
    horario: "11h30 - 00h",
    diferenciais: ["Música ao vivo", "Casa histórica", "Cozinha de boteco", "No coração do centro"]
  },
  {
    id: 20,
    nome: "Veloso Bar",
    categoria: "Bar",
    emoji: "🍸",
    imagem: "",
    preco: 80,
    avaliacoes: 4.6,
    countAvaliacao: 5400,
    localizacao: "Vila Mariana, São Paulo",
    tags: ["Casal", "Caipirinha", "Coxinha"],
    descricao: "Boteco premiado famoso pelas caipirinhas autorais e pela coxinha cremosa.",
    endereco: "R. Conceição Veloso, 54 - Vila Mariana, São Paulo, SP",
    telefone: "(11) 5572-0254",
    horario: "17h30 - 00h",
    diferenciais: ["Caipirinhas autorais", "Coxinha premiada", "Ambiente animado", "Premiado pela crítica"]
  },
  {
    id: 21,
    nome: "Pizzaria Bráz",
    categoria: "Pizzaria",
    emoji: "🍕",
    imagem: "",
    preco: 90,
    avaliacoes: 4.5,
    countAvaliacao: 7200,
    localizacao: "Pinheiros, São Paulo",
    tags: ["Família", "Casal", "Forno a lenha"],
    descricao: "Rede paulistana tradicional de pizzas no forno a lenha, com massa leve e clima acolhedor.",
    endereco: "R. Sergipe, 406 - Higienópolis, São Paulo, SP",
    telefone: "(11) 3214-3337",
    horario: "18h - 00h",
    diferenciais: ["Forno a lenha", "Chopp gelado", "Tradicional", "Bom para grupos"]
  },
  {
    id: 22,
    nome: "Bacio di Latte",
    categoria: "Sorveteria",
    emoji: "🍨",
    imagem: "",
    preco: 30,
    avaliacoes: 4.7,
    countAvaliacao: 9100,
    localizacao: "Jardins, São Paulo",
    tags: ["Casal", "Família", "Gelato"],
    descricao: "Gelateria italiana com gelato artesanal feito diariamente e dezenas de sabores.",
    endereco: "R. Oscar Freire, 136 - Jardins, São Paulo, SP",
    telefone: "(11) 3081-5024",
    horario: "12h - 23h",
    diferenciais: ["Gelato artesanal", "Sabores italianos", "Feito no dia", "Na Oscar Freire"]
  },
  {
    id: 23,
    nome: "Parque Ibirapuera",
    categoria: "Parque",
    emoji: "🌳",
    imagem: "",
    preco: 0,
    avaliacoes: 4.8,
    countAvaliacao: 25000,
    localizacao: "Moema, São Paulo",
    tags: ["Família", "Ao ar livre", "Grátis"],
    descricao: "O parque urbano mais famoso de SP: lagos, ciclovia, museus e amplas áreas verdes.",
    endereco: "Av. Pedro Álvares Cabral - Vila Mariana, São Paulo, SP",
    telefone: "(11) 5573-4180",
    horario: "05h - 00h",
    diferenciais: ["Ciclovia", "Museus", "Lagos", "Gratuito"]
  },
  {
    id: 24,
    nome: "Parque Villa-Lobos",
    categoria: "Parque",
    emoji: "🚴",
    imagem: "",
    preco: 0,
    avaliacoes: 4.7,
    countAvaliacao: 11000,
    localizacao: "Alto de Pinheiros, São Paulo",
    tags: ["Amigos", "Esporte", "Grátis"],
    descricao: "Parque com quadras, pista de skate, ciclovia e gramados para esportes e piquenique.",
    endereco: "Av. Prof. Fonseca Rodrigues, 2001 - Alto de Pinheiros, São Paulo, SP",
    telefone: "(11) 2683-6302",
    horario: "05h30 - 19h",
    diferenciais: ["Quadras esportivas", "Pista de skate", "Ciclovia", "Gratuito"]
  },
  {
    id: 25,
    nome: "Shopping Iguatemi São Paulo",
    categoria: "Shopping",
    emoji: "🛍️",
    imagem: "",
    preco: 0,
    avaliacoes: 4.6,
    countAvaliacao: 32000,
    localizacao: "Jardim Paulistano, São Paulo",
    tags: ["Compras", "Cinema", "Restaurantes"],
    descricao: "O primeiro shopping do Brasil, com lojas premium, cinema e restaurantes na Faria Lima.",
    endereco: "Av. Brigadeiro Faria Lima, 2232 - Jardim Paulistano, São Paulo, SP",
    telefone: "(11) 3815-7766",
    horario: "10h - 22h",
    diferenciais: ["Lojas premium", "Cinema", "Restaurantes", "Localização nobre"]
  },
  {
    id: 26,
    nome: "Shopping Eldorado",
    categoria: "Shopping",
    emoji: "🛍️",
    imagem: "",
    preco: 0,
    avaliacoes: 4.5,
    countAvaliacao: 28000,
    localizacao: "Pinheiros, São Paulo",
    tags: ["Família", "Cinema", "Compras"],
    descricao: "Shopping amplo com cinema, parque infantil, praça de alimentação e muitas lojas.",
    endereco: "Av. Rebouças, 3970 - Pinheiros, São Paulo, SP",
    telefone: "(11) 2197-7000",
    horario: "10h - 22h",
    diferenciais: ["Cinema", "Espaço família", "Praça de alimentação", "Fácil acesso"]
  },

  /* ---------- LUGARES REAIS (Rio de Janeiro) ---------- */
  {
    id: 27,
    nome: "Confeitaria Colombo",
    categoria: "Café",
    emoji: "☕",
    imagem: "",
    preco: 70,
    avaliacoes: 4.6,
    countAvaliacao: 21000,
    localizacao: "Centro, Rio de Janeiro",
    tags: ["Casal", "Tradição", "Café da tarde"],
    descricao: "Café histórico de 1894 com arquitetura belle époque, doces clássicos e chá da tarde.",
    endereco: "R. Gonçalves Dias, 32 - Centro, Rio de Janeiro, RJ",
    telefone: "(21) 2505-1500",
    horario: "09h - 19h",
    diferenciais: ["Casa histórica", "Arquitetura belle époque", "Doces clássicos", "Chá da tarde"]
  },
  {
    id: 28,
    nome: "Bar Astor",
    categoria: "Bar",
    emoji: "🍸",
    imagem: "",
    preco: 90,
    avaliacoes: 4.5,
    countAvaliacao: 6800,
    localizacao: "Ipanema, Rio de Janeiro",
    tags: ["Casal", "Drinks", "Vista"],
    descricao: "Bar charmoso de frente para a praia de Ipanema, com coquetelaria autoral e petiscos.",
    endereco: "Av. Vieira Souto, 110 - Ipanema, Rio de Janeiro, RJ",
    telefone: "(21) 2523-0085",
    horario: "12h - 00h",
    diferenciais: ["Frente para a praia", "Coquetelaria autoral", "Petiscos", "Ambiente charmoso"]
  },
  {
    id: 29,
    nome: "Bar do Mineiro",
    categoria: "Bar",
    emoji: "🍺",
    imagem: "",
    preco: 55,
    avaliacoes: 4.5,
    countAvaliacao: 9300,
    localizacao: "Santa Teresa, Rio de Janeiro",
    tags: ["Amigos", "Feijoada", "Boteco"],
    descricao: "Boteco tradicional de Santa Teresa famoso pela feijoada e pelas fotos em preto e branco.",
    endereco: "R. Paschoal Carlos Magno, 99 - Santa Teresa, Rio de Janeiro, RJ",
    telefone: "(21) 2221-9227",
    horario: "11h - 00h",
    diferenciais: ["Feijoada tradicional", "Clima de boteco", "Cachaças", "No alto de Santa Teresa"]
  },
  {
    id: 30,
    nome: "Aprazível",
    categoria: "Restaurante",
    emoji: "🍽️",
    imagem: "",
    preco: 180,
    avaliacoes: 4.6,
    countAvaliacao: 4200,
    localizacao: "Santa Teresa, Rio de Janeiro",
    tags: ["Casal", "Vista", "Especial"],
    descricao: "Restaurante de cozinha brasileira com vista panorâmica da Baía de Guanabara em meio à mata.",
    endereco: "R. Aprazível, 62 - Santa Teresa, Rio de Janeiro, RJ",
    telefone: "(21) 2508-9174",
    horario: "12h - 22h",
    diferenciais: ["Vista panorâmica", "Cozinha brasileira", "Ambiente em meio à mata", "Ideal para casais"]
  },
  {
    id: 31,
    nome: "Parque Lage",
    categoria: "Parque",
    emoji: "🌳",
    imagem: "",
    preco: 0,
    avaliacoes: 4.8,
    countAvaliacao: 19000,
    localizacao: "Jardim Botânico, Rio de Janeiro",
    tags: ["Família", "Ao ar livre", "Grátis"],
    descricao: "Parque histórico aos pés do Corcovado, com palacete, lago e trilhas em meio à Mata Atlântica.",
    endereco: "R. Jardim Botânico, 414 - Jardim Botânico, Rio de Janeiro, RJ",
    telefone: "(21) 3257-1800",
    horario: "08h - 18h",
    diferenciais: ["Vista do Cristo", "Palacete histórico", "Trilhas", "Gratuito"]
  },
  {
    id: 32,
    nome: "Jardim Botânico do Rio",
    categoria: "Parque",
    emoji: "🌿",
    imagem: "",
    preco: 35,
    avaliacoes: 4.8,
    countAvaliacao: 33000,
    localizacao: "Jardim Botânico, Rio de Janeiro",
    tags: ["Família", "Natureza", "Casal"],
    descricao: "Jardim de 1808 com mais de 8 mil espécies, aleia de palmeiras imperiais e orquidário.",
    endereco: "R. Jardim Botânico, 1008 - Jardim Botânico, Rio de Janeiro, RJ",
    telefone: "(21) 3874-1808",
    horario: "08h - 17h",
    diferenciais: ["Palmeiras imperiais", "Orquidário", "Lago das vitórias-régias", "Patrimônio natural"]
  },
  {
    id: 33,
    nome: "Belmonte",
    categoria: "Bar",
    emoji: "🍻",
    imagem: "",
    preco: 60,
    avaliacoes: 4.4,
    countAvaliacao: 8700,
    localizacao: "Flamengo, Rio de Janeiro",
    tags: ["Amigos", "Chopp", "Boteco"],
    descricao: "Boteco carioca clássico famoso pelo chopp gelado, pastéis e empadões generosos.",
    endereco: "Praia do Flamengo, 300 - Flamengo, Rio de Janeiro, RJ",
    telefone: "(21) 2552-3349",
    horario: "11h - 02h",
    diferenciais: ["Chopp gelado", "Empadões", "Clima de boteco", "Aberto até tarde"]
  }
];

/* =========================================================
   MAPA DE CATEGORIAS
   Liga o slug da página (ex.: "bares") ao valor usado
   no campo "categoria" dos lugares (ex.: "Bar").
========================================================= */

const MAPA_CATEGORIAS = {
  bares: ["Bar"],
  restaurantes: ["Restaurante", "Lanchonete", "Pizzaria", "Café", "Sorveteria"],
  parques: ["Parque"],
  shoppings: ["Shopping"],
  festas: ["Salão de festas", "Festa"]
};

/* Retorna os lugares de uma categoria-slug (ex.: "bares"). */
function lugaresPorCategoriaSlug(slug) {
  const aceitas = MAPA_CATEGORIAS[slug] || [];
  return lugaresData.filter((lugar) => aceitas.includes(lugar.categoria));
}

/* =========================================================
   COORDENADAS (lat/lon) — usadas na busca por proximidade.
   Mantidas separadas para não poluir cada objeto.
========================================================= */
const COORDS_LUGARES = {
  1: [-23.610, -46.660],
  2: [-23.589, -46.634],
  3: [-23.564, -46.702],
  4: [-23.557, -46.597],
  5: [-23.546, -46.690],
  6: [-23.480, -46.620],
  7: [-23.585, -46.609],
  8: [-23.554, -46.660],
  9: [-23.526, -46.636],
  10: [-23.547, -46.636],
  11: [-23.587, -46.657],
  12: [-23.452, -46.630],
  13: [-22.984, -43.222],
  14: [-23.000, -43.366],
  15: [-22.999, -43.260],
  16: [-23.550, -46.750],
  17: [-23.630, -46.670],
  18: [-23.548, -46.638],
  19: [-23.5432, -46.6418],
  20: [-23.5876, -46.6358],
  21: [-23.5512, -46.6588],
  22: [-23.5618, -46.6700],
  23: [-23.5874, -46.6576],
  24: [-23.5462, -46.7253],
  25: [-23.5775, -46.6925],
  26: [-23.5713, -46.6960],
  27: [-22.9056, -43.1773],
  28: [-22.9876, -43.2008],
  29: [-22.9168, -43.1877],
  30: [-22.9215, -43.1925],
  31: [-22.9586, -43.2117],
  32: [-22.9676, -43.2227],
  33: [-22.9355, -43.1760]
};

lugaresData.forEach((lugar) => {
  const c = COORDS_LUGARES[lugar.id];
  if (c) {
    lugar.lat = c[0];
    lugar.lon = c[1];
  }
});

/* Busca um lugar pelo id. */
function lugarPorId(id) {
  return lugaresData.find((lugar) => lugar.id === Number(id));
}

/* Disponibiliza no escopo global (para páginas que não usam módulos). */
if (typeof window !== "undefined") {
  window.lugaresData = lugaresData;
  window.MAPA_CATEGORIAS = MAPA_CATEGORIAS;
  window.lugaresPorCategoriaSlug = lugaresPorCategoriaSlug;
  window.lugarPorId = lugarPorId;
}
